### ISSUE TITLE
网盘链接失效

### ISSUE THREAD

**Issue by pianpianpianpian** [AOZMH/BERT-LSTM-Chinese-Word-Segmentation#3]
您好，我希望用您的代码做一个复现，但是网盘链接已经失效
能否发一个新的链接？
（方便的话能否用百度网盘？

**Comment by AOZMH** [comment]
我已经在readme里更新了网盘链接，这回开的有效期挺长的（到2024年）。
我没有百度网盘会员，所以上传太慢了，请问你可以使用现在这个链接嘛？

**Comment by pianpianpianpian** [comment]
谢谢你这么迅速的回复！
并不需要北大账户就能下载，已经下载成功了！
谢谢！
